theme: minima
title: JEAN ECKELBERG
author: <a href="https://soundcloud.com/titaneproductions">SoundCloud</a>
header_pages:
 - index.md
 - about.md
 - portfolio.md
 - contact.md
linkedin_username: jean-eckelberg-943025172
soundcloud_username: titaneproductions
