theme: minima
title: JEAN ECKELBERG
author: LinkedIn- https://www.linkedin.com/in/jean-eckelberg-943025172/    SoundCloud- https://soundcloud.com/titaneproductions
header_pages:
 - index.md
 - about.md
 - portfolio.md
 - contact.md
linkedin_username: jean-eckelberg-943025172
soundcloud_username: titaneproductions
